### ISSUE TITLE
More iPhones than the iPhone X have no home button

### ISSUE THREAD

**Issue by djcarter85** [s-thom/howtoscreenshot#10]
On [the iOS page](https://screenshot.help/ios) it says that for iPhone X users the procedure is different as it has no home button. Most of the current iPhones have no home button - would it make more sense to switch the order? Or perhaps just to remove reference to the iPhone X as there are many iPhones now with no home button.

**Comment by s-thom** [comment]
That's a good idea. This was written when the iPhone X had recently come out, so I had no idea what future phones from Apple would look like.

**Comment by s-thom** [comment]
I've pushed a quick change to swap the order of the entries on the iOS page.
