### ISSUE TITLE
Android guide isn't necessarily correct

### ISSUE THREAD

**Issue by FreesphereTom** [s-thom/howtoscreenshot#18]
Some Android devices are only quick press and release of the volume down and power buttons (same as iOS), rather than hold. This is most notable on (unsurprisingly) Samsung devices, which are one of the biggest shares in the market.

If you hold on such devices, it brings up the power menu.

**Comment by s-thom** [comment]
Nice find! I only recently switched to a Samsung phone from a Pixel, and hadn't noticed the screenshot shortcut being different.

I'll see if I can put something together to have both methods documented, and if I can find if other manufacturers also use the short press. Thanks again for opening the issue!

**Comment by s-thom** [comment]
I've done a quick change to the Android page. It now has the Samsung method at the top, given they are the largest device manufacturer, with a note mentioning the hold method.
