### ISSUE TITLE
Some Windows refinements are needed

### ISSUE THREAD

**Issue by bem13** [s-thom/howtoscreenshot#21]
Hello! I linked your site in a Reddit comment and got some feedback from /u/Charlie7Mason [here](https://www.reddit.com/r/flightsim/comments/10fdujw/ermergency/j4zbetf/), which I'd like to "forward" to you.

- Win + PrtSc does not mention that it also saves the screenshot as a file to C:\Users\YourUserName\Pictures\Screenshots

- Game bar shortcut does not mention Win + Alt + PrtSc, which saves the screenshot as a file to C:\Users\YourUserName\Videos\Captures

It would be great if you could add these.

**Comment by s-thom** [comment]
Awesome, thanks for forwarding these to me. I'll see if I can make time to add those points in this weekend

**Comment by s-thom** [comment]
I've updated the Windows page to address the points you've forwarded here. Thanks again for letting me know!
