### ISSUE TITLE
Instructions for Arch Linux

### ISSUE THREAD

**Issue by bwwq** [s-thom/howtoscreenshot#24]
I was excited to finally take a screenshot in Arch Linux, but none of the solutions on (you)r website worked for me. Please fix this for Arch Linux users. (I use Arch btw.)

**Comment by s-thom** [comment]
Ahh, yeah. The current instructions are for GNOME environments or other environments with `gnome-screenshot` installed (which I assume relies on GNOME or at least something similar to it). Which desktop environment are you using?

The [Arch wiki page](https://wiki.archlinux.org/title/Screen_capture) lists some screen capture packages you can install, but there's no mention of keyboard shortcuts except for `gnome-screenshot`. An interim solution could be to state that the instructions only apply to desktop environments with `gnome-screenshot` installed.

---

As an aside, Minecraft has its own built-in screenshotting with `F2`. The files get stored in your `.minecraft/screenshots` directory. Clicking the link that appears in chat should open the file directly.
