### ISSUE TITLE
Instructions for Chromebooks (Chrome OS)

### ISSUE THREAD

**Issue by IsaacHatton** [s-thom/howtoscreenshot#26]
Please can you add instructions for how to screenshot on a Chromebook:
https://support.google.com/chromebook/answer/10474268

From my experience, I haven't seen many Chromebooks with a screenshot key, so I would probably use these:
1) press Shift + Ctrl + Show windows (F5 position on a normal keyboard)
2) In the menu at the bottom, select Screenshot 
3) Screenshots get saved to your “Downloads” folder.

Thank you

**Comment by s-thom** [comment]
I think this (and also the Steam Deck from #15) would be a good idea to add. I probably don't have the time and energy to be able to do that any time soon, but I do want you to know I have seen this request.

**Comment by s-thom** [comment]
Solved in #37
