### ISSUE TITLE
Detection of platform with JavaScript

### ISSUE THREAD

**Issue by IsaacHatton** [s-thom/howtoscreenshot#27]
I know you want to ensure that it doesn't require JavaScript, but would it be ok if there was a script that tries to guess at what platform the user is on, and then displays some text saying "We think that you are using a __ device" at the top, and with the platform in question highlighted slightly, to prompt users who don't know what type of device they have. If the user doesn't have JavaScript, it will fail silently.

This would be especially useful, as some users in my experience don't know that iPads run iOS for example.

If you are happy for the project to have a little bit of JavaScript, I can have a go at it, or you can see at https://stackoverflow.com/questions/9514179/how-to-find-the-operating-system-details-using-javascript how it can be done fairly accurately.

**Comment by s-thom** [comment]
I think that's fine to add. If you want to have a go at it, then I don't see any reason why I would stop you from having a go 😄 

I like your idea of just having a message to say which browser the user is using, and have a link to the appropriate page. It definitely shouldn't automatically redirect the user to a page; most of the visitors are on mobile devices but looking at the Windows or Linux pages (well, most never make it off the home page...). I think a small and simpler "You are using [\_\_\_](#link-to-os)" would fit the more minimal style of this website, but I'm also interested in what ideas you have for it.

If you need another implementation to go off, the [`detect-browser`](https://www.npmjs.com/package/detect-browser) package seems to use [a list of regexes on the User Agent string](https://github.com/DamonOehlman/detect-browser/blob/546e6f1348375d8a486f21da07b20717267f6c49/src/index.ts#L174). There is also the [`navigator.userAgentData.platform` property](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorUAData/platform) that's part of the [User Agent Client Hints API](https://developer.mozilla.org/en-US/docs/Web/API/User-Agent_Client_Hints_API). It has been implemented in Chromium-based browsers, but not yet in Firefox or Safari. It would be much more reliable than user agent sniffing, given the plans by browser vendors to freeze user agent strings in the near future.

**Comment by s-thom** [comment]
Closing as the PR has been merged.
