### ISSUE TITLE
Windows:  Windows, Shift and S

### ISSUE THREAD

**Issue by bobslaede** [s-thom/howtoscreenshot#9]
Does not save the screenshots to a folder in My Pictures. Only puts it in the clipboard. 

![image](https://user-images.githubusercontent.com/437918/133396741-524ef1bb-8e8f-4c75-8718-26fcc5db19ba.png)

Snipping tool version 10.2008.2277.0

**Comment by s-thom** [comment]
Sorry it took so long for me to get back to this project. You're absolutely right, it doesn't save by default and this was a setting I had turned on for my machine and forgotten it was the default. I also can't find that option anymore 🤷‍♂️

I've removed references to saving the file, except for using the Snip & Sketch app itself. Thanks for letting me know it needed to be updated!
